lancerJeu()
/*let inputEcriture = document.getElementById('inputEcriture')
console.log(inputEcriture)
let btnValiderMot = document.getElementById('btnValiderMot')
console.log(btnValiderMot)
let divZoneProposition = document.querySelector('.zoneProposition')
console.log(divZoneProposition)
let spanScore = document.querySelector('.zoneScore span')
console.log(spanScore)
let listBtnRadio = document.querySelectorAll('.zoneOptions input')
console.log(listBtnRadio)*/